[package]
name = "rollup_lib"
type = "lib"
authors = [""]
compiler_version = ">=0.18.0"

[dependencies]
bignum = { git = "https://github.com/noir-lang/noir-bignum", tag = "v0.8.2" }
bigcurve = { git = "https://github.com/noir-lang/noir_bigcurve", tag = "v0.12.0" }
types = { path = "../types" }
parity_lib = { path = "../parity-lib" }
blob = { path = "../blob" }
poseidon = { git = "https://github.com/noir-lang/poseidon", tag = "v0.1.1" }
