apiVersion: 1
muteTimes:
    - orgId: 1
      name: nightly_deployment
      time_intervals:
        - times:
            - start_time: "04:00"
              end_time: "05:00"
          weekdays: [monday, tuesday, wednesday, thursday, friday, saturday, sunday]
