global:
  aztecImage:
    repository: aztecprotocol/aztec
    tag: latest
    pullPolicy: IfNotPresent
  kubectlImage:
    repository: registry.suse.com/suse/kubectl
    tag: 1.33
    pullPolicy: Always

mnemonic:
  value: ""
  fromSecret:
    name: ""
    key: mnemonic

attesters:
  attestersPerNode: 1
  nodeCount: 1
  mnemonicStartIndex: 2000
  keyStoreSecret:
    create: true
    name: "" # if empty name will be generated based on Release.Name
  addressConfigMap:
    create: true
    name: "" # if empty name will be generated based on Release.Name

publishers:
  perValidatorKey: 1
  mnemonicStartIndex: 5000
  keyStoreSecret:
    create: true
    name: "" # if empty name will be generated based on Release.Name
  addressConfigMap:
    create: true
    name: "" # if empty name will be generated based on Release.Name

provers:
  proverCount: 1
  publishersPerProver: 1
  mnemonicStartIndex: 8000
  keyStoreSecret:
    create: true
    name: "" # if empty name will be generated based on Release.Name
  addressConfigMap:
    create: true
    name: "" # if empty name will be generated based on Release.Name

keystores:
  secretName: "" # if empty, will be generated as {Release.Name}-keystores

serviceAccount:
  create: true
  name: "" # leave empty to generate a name based on Release.Name
  annotations: {}
