[package]
name = "counter_contract"
authors = [""]
compiler_version = ">=0.25.0"
type = "contract"

[dependencies]
aztec = { path = "../../../../noir-projects/aztec-nr/aztec" }
easy_private_state = { path = "../../../../noir-projects/aztec-nr/easy-private-state" }
