[package]
name = "bb_rs"
version = "2.0.3"
edition = "2021"
authors = ["Bartosz Nowak", "Th√©o Madzou"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.58"
tracing = "0.1"
tracing-subscriber = "0.3"
num-bigint = "0.4"
rmp-serde = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"

[build-dependencies]
bindgen = "0.72.1"
cmake = "0.1.50"
