global:
  aztecRollupVersion: "canonical"
  aztecNetwork: ""
  customAztecNetwork:
    enabled: false

  l1ExecutionUrls: []
  l1ConsensusUrls: []
  l1ConsensusHostApiKeys: []
  l1ConsensusHostApiKeyHeaders: []

node:
  nodeType: "prover-node"
  mnemonic: "test test test test test test test test test test test junk"
  mnemonicStartIndex: 1000
  privateKey:

  persistence:
    enabled: false
  statefulSet:
    enabled: true

  replicaCount: 1

  node:
    env:
      OTEL_SERVICE_NAME: "prover-node"
      PROVER_AGENT_COUNT: 0
      # Set this to your web3signer URL (e.g. http://web3signer.namespace.svc.cluster.local:9000/)
      WEB3_SIGNER_URL: ""
      # Derivation for publisher addresses when using web3signer
      PUBLISHERS_PER_PROVER: "1"
      PUBLISHER_KEY_INDEX_START: "8000"
    web3signerUrl: ""

    preStartScript: |
      export TX_COLLECTION_NODE_RPC_URLS=$(bash /scripts/resolve-node-hosts.sh $NODE_HOSTS)
      source /scripts/setup-prover-keystore.sh

    startCmd:
      - --prover-node
      - --archiver

    hostNetwork: true

    configMap:
      envEnabled: true
    secret:
      envEnabled: true

  service:
    p2p:
      enabled: true
      nodePortEnabled: false
    admin:
      enabled: true
    headless:
      enabled: false

broker:
  nodeType: "prover-broker"
  replicaCount: 1
  persistence:
    enabled: false
  statefulSet:
    enabled: true

  node:
    env:
      OTEL_SERVICE_NAME: "prover-broker"
    startCmd:
      - --prover-broker

  hostNetwork: false

  service:
    p2p:
      enabled: false
      nodePortEnabled: false
  rbac:
    create: false
  serviceAccount:
    create: false

agent:
  nodeType: "prover-agent"
  replicaCount: 1

  persistence:
    enabled: false

  statefulSet:
    enabled: false

  node:
    env:
      OTEL_SERVICE_NAME: "prover-agent"
    configMap:
      envEnabled: true
    startCmd:
      - --prover-agent

  service:
    p2p:
      enabled: false
      nodePortEnabled: false

  rbac:
    create: false
  serviceAccount:
    create: false
